dist: trusty
language: node_js
cache:
  directories:
    - node_modules

node_js:
  - "6"

before_install:
  - npm prune
  - npm update

install:
  - npm install

script:
  - npm test
  - npm run build:prod
