export const GET_SITES = 'GET_SITES';
export const GET_SITE = 'GET_SITE';
export const SET_ACTIVE_SITE = 'SET_ACTIVE_SITE';
export const SET_ACTIVE_MODEL = 'SET_ACTIVE_MODEL';
export const UPDATE_SITE = 'UPDATE_SITE';
export const CREATE_SITE = 'CREATE_SITE';
export const DELETE_SITE = 'DELETE_SITE';

export const GET_MODELS = 'GET_MODELS';
export const GET_MODEL = 'GET_MODEL';
export const UPDATE_MODEL = 'UPDATE_MODEL';
export const CREATE_MODEL = 'CREATE_MODEL';
export const DELETE_MODEL = 'DELETE_MODEL';

export const GET_CONTENT = 'GET_CONTENT';
export const GET_CONTENT_ITEM = 'GET_CONTENT_ITEM';
export const CREATE_CONTENT = 'CREATE_CONTENT';
export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const DELETE_CONTENT = 'DELETE_CONTENT';
export const SET_ACTIVE_CONTENTITEM = 'SET_ACTIVE_CONTENTITEM';
